/**
 * The flag pool: 195 sovereign states, their Georgian names, and a region.
 *
 * Georgian labels come from Wikidata: the `ka` label of every item that is an
 * instance of "sovereign state" and carries an ISO 3166-1 alpha-2 code, with
 * eight hand edits recorded below. Extraction is one-off and the result lives
 * here rather than in Postgres: this game reports its own score like სნეიკი
 * does, so there is no answer key worth hiding server-side, and bundling means
 * the game works with no network beyond the app itself.
 *
 * HAND EDITS, all deliberate:
 *   SZ  სვაზილენდი → ესვატინი        the country renamed in 2018; the source label is stale
 *   US, CN, NL, IE, ZA, KM, PS       official name → the common one, so a button reads
 *                                    "აშშ" rather than "ამერიკის შეერთებული შტატები"
 *
 * DELIBERATELY LEFT FORMAL: CD/CG (the two Congos) and DO (against DM). Their
 * full names are the only thing distinguishing them, and they will land as each
 * other's distractors constantly.
 *
 *  drives distractor choice — three wrong answers are drawn from the
 * same region as the right one, because Slovakia against Brazil is not a
 * question. Every region holds at least 14 countries, so a draw of four never
 * runs short.
 */

export interface Country {
  /** ISO 3166-1 alpha-2, uppercase. Also the flag asset key. */
  code: string;
  /** Georgian name, as shown on the answer buttons. */
  ka: string;
  /** English name — never rendered, kept so the list stays reviewable. */
  en: string;
  region: string;
}

export const COUNTRIES: readonly Country[] = [
  // ---- აზია ----
  { code: 'AF',  ka: 'ავღანეთი',                        en: "Afghanistan",                         region: 'აზია' },
  { code: 'AZ',  ka: 'აზერბაიჯანი',                     en: "Azerbaijan",                          region: 'აზია' },
  { code: 'AE',  ka: 'არაბთა გაერთიანებული საამიროები', en: "United Arab Emirates",                region: 'აზია' },
  { code: 'TL',  ka: 'აღმოსავლეთი ტიმორი',              en: "Timor-Leste",                         region: 'აზია' },
  { code: 'BD',  ka: 'ბანგლადეში',                      en: "Bangladesh",                          region: 'აზია' },
  { code: 'BH',  ka: 'ბაჰრეინი',                        en: "Bahrain",                             region: 'აზია' },
  { code: 'BN',  ka: 'ბრუნეი',                          en: "Brunei",                              region: 'აზია' },
  { code: 'BT',  ka: 'ბჰუტანი',                         en: "Bhutan",                              region: 'აზია' },
  { code: 'IQ',  ka: 'ერაყი',                           en: "Iraq",                                region: 'აზია' },
  { code: 'VN',  ka: 'ვიეტნამი',                        en: "Vietnam",                             region: 'აზია' },
  { code: 'TR',  ka: 'თურქეთი',                         en: "Turkey",                              region: 'აზია' },
  { code: 'TM',  ka: 'თურქმენეთი',                      en: "Turkmenistan",                        region: 'აზია' },
  { code: 'JP',  ka: 'იაპონია',                         en: "Japan",                               region: 'აზია' },
  { code: 'YE',  ka: 'იემენი',                          en: "Yemen",                               region: 'აზია' },
  { code: 'IN',  ka: 'ინდოეთი',                         en: "India",                               region: 'აზია' },
  { code: 'ID',  ka: 'ინდონეზია',                       en: "Indonesia",                           region: 'აზია' },
  { code: 'JO',  ka: 'იორდანია',                        en: "Jordan",                              region: 'აზია' },
  { code: 'IR',  ka: 'ირანი',                           en: "Iran",                                region: 'აზია' },
  { code: 'IL',  ka: 'ისრაელი',                         en: "Israel",                              region: 'აზია' },
  { code: 'KH',  ka: 'კამბოჯა',                         en: "Cambodia",                            region: 'აზია' },
  { code: 'QA',  ka: 'კატარი',                          en: "Qatar",                               region: 'აზია' },
  { code: 'LA',  ka: 'ლაოსი',                           en: "Laos",                                region: 'აზია' },
  { code: 'LB',  ka: 'ლიბანი',                          en: "Lebanon",                             region: 'აზია' },
  { code: 'MY',  ka: 'მალაიზია',                        en: "Malaysia",                            region: 'აზია' },
  { code: 'MV',  ka: 'მალდივები',                       en: "Maldives",                            region: 'აზია' },
  { code: 'MM',  ka: 'მიანმარი',                        en: "Myanmar",                             region: 'აზია' },
  { code: 'MN',  ka: 'მონღოლეთი',                       en: "Mongolia",                            region: 'აზია' },
  { code: 'NP',  ka: 'ნეპალი',                          en: "Nepal",                               region: 'აზია' },
  { code: 'OM',  ka: 'ომანი',                           en: "Oman",                                region: 'აზია' },
  { code: 'PK',  ka: 'პაკისტანი',                       en: "Pakistan",                            region: 'აზია' },
  { code: 'PS',  ka: 'პალესტინა',                       en: "Palestine",                           region: 'აზია' },
  { code: 'KR',  ka: 'სამხრეთი კორეა',                  en: "South Korea",                         region: 'აზია' },
  { code: 'SA',  ka: 'საუდის არაბეთი',                  en: "Saudi Arabia",                        region: 'აზია' },
  { code: 'SG',  ka: 'სინგაპური',                       en: "Singapore",                           region: 'აზია' },
  { code: 'SY',  ka: 'სირია',                           en: "Syria",                               region: 'აზია' },
  { code: 'AM',  ka: 'სომხეთი',                         en: "Armenia",                             region: 'აზია' },
  { code: 'TW',  ka: 'ტაივანი',                         en: "Taiwan",                              region: 'აზია' },
  { code: 'TH',  ka: 'ტაილანდი',                        en: "Thailand",                            region: 'აზია' },
  { code: 'TJ',  ka: 'ტაჯიკეთი',                        en: "Tajikistan",                          region: 'აზია' },
  { code: 'UZ',  ka: 'უზბეკეთი',                        en: "Uzbekistan",                          region: 'აზია' },
  { code: 'PH',  ka: 'ფილიპინები',                      en: "Philippines",                         region: 'აზია' },
  { code: 'KW',  ka: 'ქუვეითი',                         en: "Kuwait",                              region: 'აზია' },
  { code: 'KZ',  ka: 'ყაზახეთი',                        en: "Kazakhstan",                          region: 'აზია' },
  { code: 'KG',  ka: 'ყირგიზეთი',                       en: "Kyrgyzstan",                          region: 'აზია' },
  { code: 'LK',  ka: 'შრი-ლანკა',                       en: "Sri Lanka",                           region: 'აზია' },
  { code: 'CN',  ka: 'ჩინეთი',                          en: "People's Republic of China",          region: 'აზია' },
  { code: 'KP',  ka: 'ჩრდილოეთი კორეა',                 en: "North Korea",                         region: 'აზია' },
  // ---- აფრიკა ----
  { code: 'DZ',  ka: 'ალჟირი',                          en: "Algeria",                             region: 'აფრიკა' },
  { code: 'AO',  ka: 'ანგოლა',                          en: "Angola",                              region: 'აფრიკა' },
  { code: 'BJ',  ka: 'ბენინი',                          en: "Benin",                               region: 'აფრიკა' },
  { code: 'BW',  ka: 'ბოტსვანა',                        en: "Botswana",                            region: 'აფრიკა' },
  { code: 'BF',  ka: 'ბურკინა-ფასო',                    en: "Burkina Faso",                        region: 'აფრიკა' },
  { code: 'BI',  ka: 'ბურუნდი',                         en: "Burundi",                             region: 'აფრიკა' },
  { code: 'GA',  ka: 'გაბონი',                          en: "Gabon",                               region: 'აფრიკა' },
  { code: 'GM',  ka: 'გამბია',                          en: "The Gambia",                          region: 'აფრიკა' },
  { code: 'GH',  ka: 'განა',                            en: "Ghana",                               region: 'აფრიკა' },
  { code: 'GN',  ka: 'გვინეა',                          en: "Guinea",                              region: 'აფრიკა' },
  { code: 'GW',  ka: 'გვინეა-ბისაუ',                    en: "Guinea-Bissau",                       region: 'აფრიკა' },
  { code: 'EG',  ka: 'ეგვიპტე',                         en: "Egypt",                               region: 'აფრიკა' },
  { code: 'ET',  ka: 'ეთიოპია',                         en: "Ethiopia",                            region: 'აფრიკა' },
  { code: 'GQ',  ka: 'ეკვატორული გვინეა',               en: "Equatorial Guinea",                   region: 'აფრიკა' },
  { code: 'ER',  ka: 'ერიტრეა',                         en: "Eritrea",                             region: 'აფრიკა' },
  { code: 'SZ',  ka: 'ესვატინი',                        en: "Eswatini",                            region: 'აფრიკა' },
  { code: 'ZM',  ka: 'ზამბია',                          en: "Zambia",                              region: 'აფრიკა' },
  { code: 'ZW',  ka: 'ზიმბაბვე',                        en: "Zimbabwe",                            region: 'აფრიკა' },
  { code: 'CV',  ka: 'კაბო-ვერდე',                      en: "Cape Verde",                          region: 'აფრიკა' },
  { code: 'CM',  ka: 'კამერუნი',                        en: "Cameroon",                            region: 'აფრიკა' },
  { code: 'KE',  ka: 'კენია',                           en: "Kenya",                               region: 'აფრიკა' },
  { code: 'KM',  ka: 'კომორის კუნძულები',               en: "Comoros",                             region: 'აფრიკა' },
  { code: 'CD',  ka: 'კონგოს დემოკრატიული რესპუბლიკა',  en: "Democratic Republic of the Congo",    region: 'აფრიკა' },
  { code: 'CG',  ka: 'კონგოს რესპუბლიკა',               en: "Republic of the Congo",               region: 'აფრიკა' },
  { code: 'CI',  ka: 'კოტ-დ’ივუარი',                    en: "Ivory Coast",                         region: 'აფრიკა' },
  { code: 'LS',  ka: 'ლესოთო',                          en: "Lesotho",                             region: 'აფრიკა' },
  { code: 'LR',  ka: 'ლიბერია',                         en: "Liberia",                             region: 'აფრიკა' },
  { code: 'LY',  ka: 'ლიბია',                           en: "Libya",                               region: 'აფრიკა' },
  { code: 'MG',  ka: 'მადაგასკარი',                     en: "Madagascar",                          region: 'აფრიკა' },
  { code: 'MU',  ka: 'მავრიკი',                         en: "Mauritius",                           region: 'აფრიკა' },
  { code: 'MR',  ka: 'მავრიტანია',                      en: "Mauritania",                          region: 'აფრიკა' },
  { code: 'MW',  ka: 'მალავი',                          en: "Malawi",                              region: 'აფრიკა' },
  { code: 'ML',  ka: 'მალი',                            en: "Mali",                                region: 'აფრიკა' },
  { code: 'MA',  ka: 'მაროკო',                          en: "Morocco",                             region: 'აფრიკა' },
  { code: 'MZ',  ka: 'მოზამბიკი',                       en: "Mozambique",                          region: 'აფრიკა' },
  { code: 'NA',  ka: 'ნამიბია',                         en: "Namibia",                             region: 'აფრიკა' },
  { code: 'NE',  ka: 'ნიგერი',                          en: "Niger",                               region: 'აფრიკა' },
  { code: 'NG',  ka: 'ნიგერია',                         en: "Nigeria",                             region: 'აფრიკა' },
  { code: 'RW',  ka: 'რუანდა',                          en: "Rwanda",                              region: 'აფრიკა' },
  { code: 'ZA',  ka: 'სამხრეთ აფრიკა',                  en: "South Africa",                        region: 'აფრიკა' },
  { code: 'SS',  ka: 'სამხრეთი სუდანი',                 en: "South Sudan",                         region: 'აფრიკა' },
  { code: 'ST',  ka: 'სან-ტომე და პრინსიპი',            en: "São Tomé and Príncipe",               region: 'აფრიკა' },
  { code: 'SC',  ka: 'სეიშელის კუნძულები',              en: "Seychelles",                          region: 'აფრიკა' },
  { code: 'SN',  ka: 'სენეგალი',                        en: "Senegal",                             region: 'აფრიკა' },
  { code: 'SL',  ka: 'სიერა-ლეონე',                     en: "Sierra Leone",                        region: 'აფრიკა' },
  { code: 'SO',  ka: 'სომალი',                          en: "Somalia",                             region: 'აფრიკა' },
  { code: 'SD',  ka: 'სუდანი',                          en: "Sudan",                               region: 'აფრიკა' },
  { code: 'TZ',  ka: 'ტანზანია',                        en: "Tanzania",                            region: 'აფრიკა' },
  { code: 'TG',  ka: 'ტოგო',                            en: "Togo",                                region: 'აფრიკა' },
  { code: 'TN',  ka: 'ტუნისი',                          en: "Tunisia",                             region: 'აფრიკა' },
  { code: 'UG',  ka: 'უგანდა',                          en: "Uganda",                              region: 'აფრიკა' },
  { code: 'TD',  ka: 'ჩადი',                            en: "Chad",                                region: 'აფრიკა' },
  { code: 'CF',  ka: 'ცენტრალური აფრიკის რესპუბლიკა',   en: "Central African Republic",            region: 'აფრიკა' },
  { code: 'DJ',  ka: 'ჯიბუტი',                          en: "Djibouti",                            region: 'აფრიკა' },
  // ---- ევროპა ----
  { code: 'AT',  ka: 'ავსტრია',                         en: "Austria",                             region: 'ევროპა' },
  { code: 'AL',  ka: 'ალბანეთი',                        en: "Albania",                             region: 'ევროპა' },
  { code: 'AD',  ka: 'ანდორა',                          en: "Andorra",                             region: 'ევროპა' },
  { code: 'BY',  ka: 'ბელარუსი',                        en: "Belarus",                             region: 'ევროპა' },
  { code: 'BE',  ka: 'ბელგია',                          en: "Belgium",                             region: 'ევროპა' },
  { code: 'BA',  ka: 'ბოსნია და ჰერცეგოვინა',           en: "Bosnia and Herzegovina",              region: 'ევროპა' },
  { code: 'BG',  ka: 'ბულგარეთი',                       en: "Bulgaria",                            region: 'ევროპა' },
  { code: 'GB',  ka: 'გაერთიანებული სამეფო',            en: "United Kingdom",                      region: 'ევროპა' },
  { code: 'DE',  ka: 'გერმანია',                        en: "Germany",                             region: 'ევროპა' },
  { code: 'ES',  ka: 'ესპანეთი',                        en: "Spain",                               region: 'ევროპა' },
  { code: 'EE',  ka: 'ესტონეთი',                        en: "Estonia",                             region: 'ევროპა' },
  { code: 'IE',  ka: 'ირლანდია',                        en: "Ireland",                             region: 'ევროპა' },
  { code: 'IS',  ka: 'ისლანდია',                        en: "Iceland",                             region: 'ევროპა' },
  { code: 'IT',  ka: 'იტალია',                          en: "Italy",                               region: 'ევროპა' },
  { code: 'CY',  ka: 'კვიპროსი',                        en: "Cyprus",                              region: 'ევროპა' },
  { code: 'XK',  ka: 'კოსოვო',                          en: "Kosovo",                              region: 'ევროპა' },
  { code: 'LV',  ka: 'ლატვია',                          en: "Latvia",                              region: 'ევროპა' },
  { code: 'LT',  ka: 'ლიეტუვა',                         en: "Lithuania",                           region: 'ევროპა' },
  { code: 'LI',  ka: 'ლიხტენშტაინი',                    en: "Liechtenstein",                       region: 'ევროპა' },
  { code: 'LU',  ka: 'ლუქსემბურგი',                     en: "Luxembourg",                          region: 'ევროპა' },
  { code: 'MT',  ka: 'მალტა',                           en: "Malta",                               region: 'ევროპა' },
  { code: 'MD',  ka: 'მოლდოვა',                         en: "Moldova",                             region: 'ევროპა' },
  { code: 'MC',  ka: 'მონაკო',                          en: "Monaco",                              region: 'ევროპა' },
  { code: 'ME',  ka: 'მონტენეგრო',                      en: "Montenegro",                          region: 'ევროპა' },
  { code: 'NL',  ka: 'ნიდერლანდები',                    en: "Kingdom of the Netherlands",          region: 'ევროპა' },
  { code: 'NO',  ka: 'ნორვეგია',                        en: "Norway",                              region: 'ევროპა' },
  { code: 'PL',  ka: 'პოლონეთი',                        en: "Poland",                              region: 'ევროპა' },
  { code: 'PT',  ka: 'პორტუგალია',                      en: "Portugal",                            region: 'ევროპა' },
  { code: 'RO',  ka: 'რუმინეთი',                        en: "Romania",                             region: 'ევროპა' },
  { code: 'RU',  ka: 'რუსეთი',                          en: "Russia",                              region: 'ევროპა' },
  { code: 'GR',  ka: 'საბერძნეთი',                      en: "Greece",                              region: 'ევროპა' },
  { code: 'SM',  ka: 'სან-მარინო',                      en: "San Marino",                          region: 'ევროპა' },
  { code: 'FR',  ka: 'საფრანგეთი',                      en: "France",                              region: 'ევროპა' },
  { code: 'GE',  ka: 'საქართველო',                      en: "Georgia",                             region: 'ევროპა' },
  { code: 'RS',  ka: 'სერბეთი',                         en: "Serbia",                              region: 'ევროპა' },
  { code: 'SK',  ka: 'სლოვაკეთი',                       en: "Slovakia",                            region: 'ევროპა' },
  { code: 'SI',  ka: 'სლოვენია',                        en: "Slovenia",                            region: 'ევროპა' },
  { code: 'UA',  ka: 'უკრაინა',                         en: "Ukraine",                             region: 'ევროპა' },
  { code: 'HU',  ka: 'უნგრეთი',                         en: "Hungary",                             region: 'ევროპა' },
  { code: 'FI',  ka: 'ფინეთი',                          en: "Finland",                             region: 'ევროპა' },
  { code: 'SE',  ka: 'შვედეთი',                         en: "Sweden",                              region: 'ევროპა' },
  { code: 'CH',  ka: 'შვეიცარია',                       en: "Switzerland",                         region: 'ევროპა' },
  { code: 'CZ',  ka: 'ჩეხეთი',                          en: "Czech Republic",                      region: 'ევროპა' },
  { code: 'MK',  ka: 'ჩრდილოეთი მაკედონია',             en: "North Macedonia",                     region: 'ევროპა' },
  { code: 'HR',  ka: 'ხორვატია',                        en: "Croatia",                             region: 'ევროპა' },
  // ---- ოკეანეთი ----
  { code: 'AU',  ka: 'ავსტრალია',                       en: "Australia",                           region: 'ოკეანეთი' },
  { code: 'NZ',  ka: 'ახალი ზელანდია',                  en: "New Zealand",                         region: 'ოკეანეთი' },
  { code: 'VU',  ka: 'ვანუატუ',                         en: "Vanuatu",                             region: 'ოკეანეთი' },
  { code: 'KI',  ka: 'კირიბატი',                        en: "Kiribati",                            region: 'ოკეანეთი' },
  { code: 'MH',  ka: 'მარშალის კუნძულები',              en: "Marshall Islands",                    region: 'ოკეანეთი' },
  { code: 'FM',  ka: 'მიკრონეზია',                      en: "Federated States of Micronesia",      region: 'ოკეანეთი' },
  { code: 'NR',  ka: 'ნაურუ',                           en: "Nauru",                               region: 'ოკეანეთი' },
  { code: 'PW',  ka: 'პალაუ',                           en: "Palau",                               region: 'ოკეანეთი' },
  { code: 'PG',  ka: 'პაპუა-ახალი გვინეა',              en: "Papua New Guinea",                    region: 'ოკეანეთი' },
  { code: 'WS',  ka: 'სამოა',                           en: "Samoa",                               region: 'ოკეანეთი' },
  { code: 'SB',  ka: 'სოლომონის კუნძულები',             en: "Solomon Islands",                     region: 'ოკეანეთი' },
  { code: 'TO',  ka: 'ტონგა',                           en: "Tonga",                               region: 'ოკეანეთი' },
  { code: 'TV',  ka: 'ტუვალუ',                          en: "Tuvalu",                              region: 'ოკეანეთი' },
  { code: 'FJ',  ka: 'ფიჯი',                            en: "Fiji",                                region: 'ოკეანეთი' },
  // ---- სამხრეთი ამერიკა ----
  { code: 'AR',  ka: 'არგენტინა',                       en: "Argentina",                           region: 'სამხრეთი ამერიკა' },
  { code: 'BO',  ka: 'ბოლივია',                         en: "Bolivia",                             region: 'სამხრეთი ამერიკა' },
  { code: 'BR',  ka: 'ბრაზილია',                        en: "Brazil",                              region: 'სამხრეთი ამერიკა' },
  { code: 'GY',  ka: 'გაიანა',                          en: "Guyana",                              region: 'სამხრეთი ამერიკა' },
  { code: 'EC',  ka: 'ეკვადორი',                        en: "Ecuador",                             region: 'სამხრეთი ამერიკა' },
  { code: 'VE',  ka: 'ვენესუელა',                       en: "Venezuela",                           region: 'სამხრეთი ამერიკა' },
  { code: 'CO',  ka: 'კოლომბია',                        en: "Colombia",                            region: 'სამხრეთი ამერიკა' },
  { code: 'PY',  ka: 'პარაგვაი',                        en: "Paraguay",                            region: 'სამხრეთი ამერიკა' },
  { code: 'PE',  ka: 'პერუ',                            en: "Peru",                                region: 'სამხრეთი ამერიკა' },
  { code: 'SR',  ka: 'სურინამი',                        en: "Suriname",                            region: 'სამხრეთი ამერიკა' },
  { code: 'UY',  ka: 'ურუგვაი',                         en: "Uruguay",                             region: 'სამხრეთი ამერიკა' },
  { code: 'CL',  ka: 'ჩილე',                            en: "Chile",                               region: 'სამხრეთი ამერიკა' },
  // ---- ჩრდილოეთი ამერიკა ----
  { code: 'AG',  ka: 'ანტიგუა და ბარბუდა',              en: "Antigua and Barbuda",                 region: 'ჩრდილოეთი ამერიკა' },
  { code: 'US',  ka: 'აშშ',                             en: "United States",                       region: 'ჩრდილოეთი ამერიკა' },
  { code: 'BB',  ka: 'ბარბადოსი',                       en: "Barbados",                            region: 'ჩრდილოეთი ამერიკა' },
  { code: 'BS',  ka: 'ბაჰამის კუნძულები',               en: "The Bahamas",                         region: 'ჩრდილოეთი ამერიკა' },
  { code: 'BZ',  ka: 'ბელიზი',                          en: "Belize",                              region: 'ჩრდილოეთი ამერიკა' },
  { code: 'GT',  ka: 'გვატემალა',                       en: "Guatemala",                           region: 'ჩრდილოეთი ამერიკა' },
  { code: 'GD',  ka: 'გრენადა',                         en: "Grenada",                             region: 'ჩრდილოეთი ამერიკა' },
  { code: 'DM',  ka: 'დომინიკა',                        en: "Dominica",                            region: 'ჩრდილოეთი ამერიკა' },
  { code: 'DO',  ka: 'დომინიკელთა რესპუბლიკა',          en: "Dominican Republic",                  region: 'ჩრდილოეთი ამერიკა' },
  { code: 'JM',  ka: 'იამაიკა',                         en: "Jamaica",                             region: 'ჩრდილოეთი ამერიკა' },
  { code: 'CA',  ka: 'კანადა',                          en: "Canada",                              region: 'ჩრდილოეთი ამერიკა' },
  { code: 'CR',  ka: 'კოსტა-რიკა',                      en: "Costa Rica",                          region: 'ჩრდილოეთი ამერიკა' },
  { code: 'CU',  ka: 'კუბა',                            en: "Cuba",                                region: 'ჩრდილოეთი ამერიკა' },
  { code: 'MX',  ka: 'მექსიკა',                         en: "Mexico",                              region: 'ჩრდილოეთი ამერიკა' },
  { code: 'NI',  ka: 'ნიკარაგუა',                       en: "Nicaragua",                           region: 'ჩრდილოეთი ამერიკა' },
  { code: 'PA',  ka: 'პანამა',                          en: "Panama",                              region: 'ჩრდილოეთი ამერიკა' },
  { code: 'SV',  ka: 'სალვადორი',                       en: "El Salvador",                         region: 'ჩრდილოეთი ამერიკა' },
  { code: 'VC',  ka: 'სენტ-ვინსენტი და გრენადინები',    en: "Saint Vincent and the Grenadines",    region: 'ჩრდილოეთი ამერიკა' },
  { code: 'KN',  ka: 'სენტ-კიტსი და ნევისი',            en: "Saint Kitts and Nevis",               region: 'ჩრდილოეთი ამერიკა' },
  { code: 'LC',  ka: 'სენტ-ლუსია',                      en: "Saint Lucia",                         region: 'ჩრდილოეთი ამერიკა' },
  { code: 'TT',  ka: 'ტრინიდადი და ტობაგო',             en: "Trinidad and Tobago",                 region: 'ჩრდილოეთი ამერიკა' },
  { code: 'HT',  ka: 'ჰაიტი',                           en: "Haiti",                               region: 'ჩრდილოეთი ამერიკა' },
  { code: 'HN',  ka: 'ჰონდურასი',                       en: "Honduras",                            region: 'ჩრდილოეთი ამერიკა' },
];
